# jekyll serve -w

name: ZEBRA.IO
description: "A fast, low-latency, low-memory footprint, web JSON-API framework."

url: http://zebra.io

markdown: redcarpet
pygments: true
cache: false

assets:
  compress:
    css: sass
    js: uglifier
