# jekyll serve -w

name: GIN.IO
description: "A fast, low-latency, low-memory footprint, web JSON-API framework."

url: http://gin.io

markdown: redcarpet
highlighter: pygments
cache: false

assets:
  compress:
    css: sass
    js: uglifier
